const data = {
    products: [
      {
        name: 'rice polished',
        slug: 'rice-polished1',
        category: 'rice',
        image: '/images/p1.jpeg', 
        price: 1000,
        countInStock: 10,
        farmerName: 'rice-by-farmer1',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality polished rice',
      },
      {
        name: 'wheet',
        slug: 'wheet1',
        category: 'wheet',
        image: '/images/p2.jpeg',
        price: 1000,
        countInStock: 20,
        farmerName: 'wheet-by-farmer2',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality wheet',
      },
      {
        name: 'rice polished',
        slug: 'rice-polished',
        category: 'rice',
        image: '/images/p3.jpeg', 
        price: 1000,
        countInStock: 0,
        farmerName: 'rice-by-farmer1',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality polished rice',
      },
      {
        name: 'wheet',
        slug: 'wheet',
        category: 'wheet',
        image: '/images/p4.jpeg',
        price: 1000,
        countInStock: 20,
        farmerName: 'wheet-by-farmer2',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality wheet',
      },
    ],
  };
  export default data;