const data = {
    products: [
      {
        //_id: '1',
        name: 'Product1',
        slug: 'rice-polished1',
        category: 'rice1',
        image: '/images/p1.jpeg', 
        price: 1000,
        countInStock: 10,
        brand: 'rice-by-farmer1',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality polished rice',
      },
      {
        //_id: '2',
        name: 'Product1',
        slug: 'wheet1',
        category: 'wheet1',
        image: '/images/p2.jpeg',
        price: 1000,
        countInStock: 20,
        brand: 'wheet-by-farmer2',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality wheet',
      },
      {
        //_id: '3',
        name: 'Product3',
        slug: 'rice-polished2',
        category: 'rice2',
        image: '/images/p3.jpeg', 
        price: 1000,
        countInStock: 0,
        brand: 'rice-by-farmer1',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality polished rice',
      },
      {
        //_id: '4',
        name: 'Product1',
        slug: 'wheet2',
        category: 'wheet2',
        image: '/images/p4.jpeg',
        price: 1000,
        countInStock: 20,
        brand: 'wheet-by-farmer2',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality wheet',
      },
    ],
  };
  export default data;