const data = {
    products: [
      {
        name: 'rice1',
        slug: 'slug1',
        category: 'category1',
        image: '/images/p1.jpeg', 
        price: 1000,
        countInStock: 10,
        brand: 'brand1',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality polished rice',
      },
      {
        name: 'rice2',
        slug: 'slug2',
        category: 'category2',
        image: '/images/p2.jpeg', 
        price: 1000,
        countInStock: 10,
        brand: 'brand2',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality wheet',
      },
      {
        name: 'wheet1',
        slug: 'slug3',
        category: 'category3',
        image: '/images/p3.jpeg', 
        price: 1000,
        countInStock: 10,
        brand: 'brand3',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality polished rice',
      },
      {
        name: 'wheet2',
        slug: 'slug4',
        category: 'category4',
        image: '/images/p4.jpeg', 
        price: 1000,
        countInStock: 10,
        brand: 'brand4',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality wheet',
      },
    ],
  };
  export default data;